server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clientsFinancialDb
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none #We dont want hibernate to create table when we start the application
    open-in-view: false #Change how database sessions are handled with regard to the open session in view pattern
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never #